# Generated by Django 5.1.5 on 2025-01-24 04:43

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('import_date', models.DateField()),
                ('batch_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('so_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('bill_to', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_engineer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('acknowledge_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledge_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_to_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_to_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='trade.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='InlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.CharField(blank=True, max_length=100, null=True)),
                ('material_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_code', models.CharField(blank=True, max_length=100, null=True)),
                ('s_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('linkage_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('imported_qty', models.IntegerField(blank=True, null=True)),
                ('exported_qty', models.IntegerField(blank=True, null=True)),
                ('revision_flag', models.BooleanField(default=False)),
                ('revision_count', models.IntegerField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('status_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('warranty_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Only USD amount', max_digits=10, null=True)),
                ('total_amount', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '-', models.F('quantity')), output_field=models.BigIntegerField())),
                ('is_active', models.BooleanField(default=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.masteritem')),
            ],
        ),
        migrations.AddField(
            model_name='importbatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='trade.masteritem'),
        ),
        migrations.CreateModel(
            name='AuthThreads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_list', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.masteritem')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('approve_status', models.CharField(default='Approver', max_length=200)),
                ('approver_flag', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('approver_stage', models.CharField(blank=True, max_length=200, null=True)),
                ('approver_level', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.masteritem')),
            ],
        ),
    ]
